# Compute images will be both slimmer and faster 
# with Ubuntu base image instead of Alpine linus:
# https://pythonspeed.com/articles/alpine-docker-python/
FROM python:3.7-slim

RUN apt-get install nvidia-settings
RUN nvidia-smi